"""Consistent, paginated PDF rendering for operational documents."""

from io import BytesIO
from typing import Iterable, Sequence

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


NAVY = colors.HexColor("#101828")
INDIGO = colors.HexColor("#3448C5")
ORANGE = colors.HexColor("#C45A3B")
SLATE = colors.HexColor("#566176")
LINE = colors.HexColor("#DDE3EA")
PALE = colors.HexColor("#F6F8FA")


def _text(value) -> str:
    if value is None or value == "":
        return "-"
    return str(value)


def build_document(
    *,
    title: str,
    number: str,
    status: str,
    metadata: Sequence[tuple[str, object]],
    columns: Sequence[str],
    rows: Iterable[Sequence[object]],
    totals: Sequence[tuple[str, object]] = (),
    notes: str | None = None,
) -> bytes:
    buffer = BytesIO()
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="DocBrand", parent=styles["Heading1"], fontName="Helvetica-Bold",
        fontSize=20, leading=23, textColor=NAVY, spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        name="DocTitle", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=9, leading=12, textColor=ORANGE, uppercase=True, spaceAfter=14,
    ))
    styles.add(ParagraphStyle(
        name="DocSmall", parent=styles["Normal"], fontName="Helvetica",
        fontSize=8, leading=11, textColor=SLATE,
    ))
    styles.add(ParagraphStyle(
        name="DocTotal", parent=styles["Normal"], fontName="Helvetica-Bold",
        fontSize=9, leading=12, textColor=NAVY, alignment=TA_RIGHT,
    ))
    styles.add(ParagraphStyle(
        name="DocTableHeader", parent=styles["DocSmall"], fontName="Helvetica-Bold",
        textColor=colors.white,
    ))
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=17 * mm,
        rightMargin=17 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"{title} {number}",
        author="Atelier Garment ERP",
    )

    def page(canvas, document):
        canvas.saveState()
        canvas.setStrokeColor(LINE)
        canvas.line(17 * mm, 13 * mm, 193 * mm, 13 * mm)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(SLATE)
        canvas.drawString(17 * mm, 8.5 * mm, "Generated by Atelier Garment ERP")
        canvas.drawRightString(193 * mm, 8.5 * mm, f"Page {document.page}")
        canvas.restoreState()

    story = [
        Paragraph("ATELIER", styles["DocBrand"]),
        Paragraph(title.upper(), styles["DocTitle"]),
    ]
    heading = Table(
        [
            [Paragraph("DOCUMENT NUMBER", styles["DocSmall"]), Paragraph("STATUS", styles["DocSmall"])],
            [Paragraph(f"<b>{_text(number)}</b>", styles["Normal"]), Paragraph(f"<b>{_text(status).upper()}</b>", styles["Normal"])],
        ],
        colWidths=[120 * mm, 56 * mm],
    )
    heading.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PALE),
        ("BOX", (0, 0), (-1, -1), .5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), .5, LINE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 9),
        ("RIGHTPADDING", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.extend([heading, Spacer(1, 7 * mm)])

    meta_rows = []
    for index in range(0, len(metadata), 2):
        pair = metadata[index:index + 2]
        cells = []
        for label, value in pair:
            cells.extend([
                Paragraph(label.upper(), styles["DocSmall"]),
                Paragraph(_text(value), styles["Normal"]),
            ])
        while len(cells) < 4:
            cells.extend(["", ""])
        meta_rows.append(cells)
    meta = Table(meta_rows, colWidths=[27 * mm, 61 * mm, 27 * mm, 61 * mm])
    meta.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), .35, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.extend([meta, Spacer(1, 8 * mm)])

    body_rows = [[Paragraph(column, styles["DocTableHeader"]) for column in columns]]
    for row in rows:
        body_rows.append([Paragraph(_text(value), styles["DocSmall"]) for value in row])
    widths = [176 * mm / len(columns)] * len(columns)
    lines = Table(body_rows, colWidths=widths, repeatRows=1)
    lines.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), .35, LINE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, PALE]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.extend([lines, Spacer(1, 6 * mm)])

    if totals:
        total_rows = [[Paragraph(label, styles["DocSmall"]), Paragraph(_text(value), styles["DocTotal"])] for label, value in totals]
        total_table = Table(total_rows, colWidths=[115 * mm, 61 * mm], hAlign="RIGHT")
        total_table.setStyle(TableStyle([
            ("LINEABOVE", (0, 0), (-1, 0), .8, INDIGO),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(total_table)
    if notes:
        story.extend([
            Spacer(1, 8 * mm),
            KeepTogether([
                Paragraph("NOTES", styles["DocSmall"]),
                Spacer(1, 2 * mm),
                Paragraph(_text(notes), styles["Normal"]),
            ]),
        ])
    doc.build(story, onFirstPage=page, onLaterPages=page)
    return buffer.getvalue()
