"""initial schema

Revision ID: 6b5281d83d4d
Revises: 
Create Date: 2026-07-22 17:48:30.991677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b5281d83d4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', 'equity', 'income', 'expense', name='accounttype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_code'), ['code'], unique=True)

    op.create_table('colour',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pantone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colour', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colour_code'), ['code'], unique=True)

    op.create_table('customer',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('billing_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_code'), ['code'], unique=True)

    op.create_table('document_sequence',
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('doc_type', 'year')
    )
    op.create_table('idempotency_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idempotency_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_key_client_key'), ['client_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_key_scope'), ['scope'], unique=False)

    op.create_table('journal_entry',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'system', name='journalsource'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'posted', 'reversed', name='journalstatus'), nullable=False),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reversal_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_entry_number'), ['entry_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_journal_entry_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_status'), ['status'], unique=False)

    op.create_table('material',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material_type', sa.Enum('fabric', 'trims', 'thread', 'labels', 'hangtags', 'packaging', 'chemicals', 'consumables', 'service', name='materialtype'), nullable=False),
    sa.Column('base_uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_to_base_factor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('lot_tracked', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('composition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weave', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_code'), ['code'], unique=True)

    op.create_table('season',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_code'), ['code'], unique=True)

    op.create_table('sizerange',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sizerange', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sizerange_code'), ['code'], unique=True)

    op.create_table('supplier',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('restricted_substance_certified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_code'), ['code'], unique=True)

    op.create_table('ap_bill',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'part_paid', 'paid', name='settlementstatus'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ap_bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ap_bill_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ap_bill_goods_receipt_id'), ['goods_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ap_bill_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ap_bill_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('journal_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_line_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_journal_entry_id'), ['journal_entry_id'], unique=False)

    op.create_table('roll',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('dye_lot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shade_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shade_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('length', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gsm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='grade'), nullable=False),
    sa.Column('warehouse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending_inspection', 'available', 'reserved', 'quarantined', 'consumed', 'rejected', name='rollstatus'), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=True),
    sa.Column('restricted_customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['restricted_customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roll_dye_lot'), ['dye_lot'], unique=False)
        batch_op.create_index(batch_op.f('ix_roll_goods_receipt_id'), ['goods_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roll_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_roll_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roll_roll_number'), ['roll_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_roll_shade_group'), ['shade_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_roll_status'), ['status'], unique=False)

    op.create_table('sales_order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incoterms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'in_production', 'shipped', 'closed', 'cancelled', name='salesorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_order_status'), ['status'], unique=False)

    op.create_table('size_range_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_range_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['size_range_id'], ['sizerange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('size_range_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_size_range_item_size_range_id'), ['size_range_id'], unique=False)

    op.create_table('style',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('style_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('size_range_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('mens', 'womens', 'boys', 'girls', 'unisex', name='gender'), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('development', 'active', 'on_hold', 'discontinued', name='stylestatus'), nullable=False),
    sa.Column('standard_sam', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['size_range_id'], ['sizerange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_style_number'), ['style_number'], unique=True)

    op.create_table('supplier_material_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.Enum('fabric', 'trims', 'thread', 'labels', 'hangtags', 'packaging', 'chemicals', 'consumables', 'service', name='materialtype'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_material_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_material_type_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('ar_invoice',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'part_paid', 'paid', name='settlementstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ar_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ar_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ar_invoice_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ar_invoice_status'), ['status'], unique=False)

    op.create_table('bom_version',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'superseded', name='bomstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_version_style_id'), ['style_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_version_version_no'), ['version_no'], unique=False)

    op.create_table('cost_sheet_version',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'superseded', name='costsheetstatus'), nullable=False),
    sa.Column('base_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sam', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sewing_cost_per_min', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sewing_efficiency_pct', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('overhead_pct', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_sheet_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_sheet_version_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_sheet_version_style_id'), ['style_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_sheet_version_version_no'), ['version_no'], unique=False)

    op.create_table('final_inspection',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('aql', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('code_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('accept_number', sa.Integer(), nullable=False),
    sa.Column('reject_number', sa.Integer(), nullable=False),
    sa.Column('defects_found', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('pending', 'passed', 'failed', name='inspectionresult'), nullable=False),
    sa.Column('inspected_date', sa.Date(), nullable=True),
    sa.Column('inspector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_inspection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_inspection_inspection_number'), ['inspection_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_final_inspection_sales_order_id'), ['sales_order_id'], unique=False)

    op.create_table('four_point_inspection',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('inspected_length', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('width_cm', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('acceptance_threshold', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('points_per_100sqyd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('result', sa.Enum('pending', 'passed', 'failed', name='inspectionresult'), nullable=False),
    sa.Column('inspected_date', sa.Date(), nullable=True),
    sa.Column('inspector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('four_point_inspection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_four_point_inspection_inspection_number'), ['inspection_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_four_point_inspection_roll_id'), ['roll_id'], unique=False)

    op.create_table('purchase_order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'partially_received', 'received', 'closed', 'cancelled', name='purchaseorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('reservation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=True),
    sa.Column('reserved_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('active', 'released', 'consumed', name='reservationstatus'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_roll_id'), ['roll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_status'), ['status'], unique=False)

    op.create_table('sales_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('packing_ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_line_colour_id'), ['colour_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_line_sales_order_id'), ['sales_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_line_style_id'), ['style_id'], unique=False)

    op.create_table('stock_ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('receipt', 'issue', 'return_to_stock', 'adjustment', 'transfer_in', 'transfer_out', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_roll_id'), ['roll_id'], unique=False)

    op.create_table('style_colourway',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.Column('buyer_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lab_dip_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_colourway', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_colourway_style_id'), ['style_id'], unique=False)

    op.create_table('bom_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_version_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=True),
    sa.Column('wastage_pct', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('optional_component', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['bom_version_id'], ['bom_version.id'], ),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_line_bom_version_id'), ['bom_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_line_material_id'), ['material_id'], unique=False)

    op.create_table('cost_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_sheet_version_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('material', 'trim', 'sewing', 'overhead', 'other', name='costcategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('wastage_pct', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['cost_sheet_version_id'], ['cost_sheet_version.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_line_cost_sheet_version_id'), ['cost_sheet_version_id'], unique=False)

    op.create_table('cut_order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=False),
    sa.Column('bom_version_id', sa.Integer(), nullable=False),
    sa.Column('fabric_material_id', sa.Integer(), nullable=False),
    sa.Column('marker_efficiency', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fabric_required', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fabric_issued', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pieces_cut', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'fabric_reserved', 'in_cutting', 'completed', 'cancelled', name='cutorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['bom_version_id'], ['bom_version.id'], ),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['fabric_material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cut_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cut_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cut_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cut_order_style_id'), ['style_id'], unique=False)

    op.create_table('four_point_defect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('penalty_points', sa.Integer(), nullable=False),
    sa.Column('position_m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['four_point_inspection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('four_point_defect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_four_point_defect_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('goods_receipt',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_goods_receipt_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('colour_id', sa.Integer(), nullable=True),
    sa.Column('ordered_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('construction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gsm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('finish', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inspection_standard', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['colour_id'], ['colour.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_line_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('sales_order_size_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('size_range_item_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('size_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('confirmed_qty', sa.Integer(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['sales_order_line.id'], ),
    sa.ForeignKeyConstraint(['size_range_item_id'], ['size_range_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_size_cell', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_size_cell_line_id'), ['line_id'], unique=False)

    op.create_table('bom_line_size_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_line_id', sa.Integer(), nullable=False),
    sa.Column('size_range_item_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('size_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumption', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bom_line_id'], ['bom_line.id'], ),
    sa.ForeignKeyConstraint(['size_range_item_id'], ['size_range_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_line_size_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_line_size_consumption_bom_line_id'), ['bom_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_line_size_consumption_size_range_item_id'), ['size_range_item_id'], unique=False)

    op.create_table('cut_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cut_order_id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cut_order_id'], ['cut_order.id'], ),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cut_issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cut_issue_cut_order_id'), ['cut_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cut_issue_roll_id'), ['roll_id'], unique=False)

    op.create_table('cut_order_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cut_order_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('cut_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cut_order_id'], ['cut_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cut_order_size', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cut_order_size_cut_order_id'), ['cut_order_id'], unique=False)

    op.create_table('goods_receipt_roll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt_roll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_roll_goods_receipt_id'), ['goods_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_roll_purchase_order_line_id'), ['purchase_order_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_roll_roll_id'), ['roll_id'], unique=False)

    op.create_table('sewing_order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cut_order_id', sa.Integer(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('produced_qty', sa.Integer(), nullable=False),
    sa.Column('sam', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'closed', name='sewingorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['cut_order_id'], ['cut_order.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sewing_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sewing_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sewing_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sewing_order_style_id'), ['style_id'], unique=False)

    op.create_table('subcontract_order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=False),
    sa.Column('process', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cut_order_id', sa.Integer(), nullable=True),
    sa.Column('sent_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'partially_received', 'received', 'closed', name='subcontractstatus'), nullable=False),
    sa.ForeignKeyConstraint(['cut_order_id'], ['cut_order.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcontract_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcontract_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_subcontract_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontract_order_subcontractor_id'), ['subcontractor_id'], unique=False)

    op.create_table('inline_inspection',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sewing_order_id', sa.Integer(), nullable=False),
    sa.Column('inspected_date', sa.Date(), nullable=True),
    sa.Column('units_checked', sa.Integer(), nullable=False),
    sa.Column('defects_found', sa.Integer(), nullable=False),
    sa.Column('dhu', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('inspector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sewing_order_id'], ['sewing_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inline_inspection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inline_inspection_inspection_number'), ['inspection_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inline_inspection_sewing_order_id'), ['sewing_order_id'], unique=False)

    op.create_table('sewing_daily_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sewing_order_id', sa.Integer(), nullable=False),
    sa.Column('output_date', sa.Date(), nullable=False),
    sa.Column('shift', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('produced_qty', sa.Integer(), nullable=False),
    sa.Column('operators', sa.Integer(), nullable=False),
    sa.Column('working_minutes', sa.Integer(), nullable=False),
    sa.Column('efficiency_pct', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('client_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sewing_order_id'], ['sewing_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sewing_daily_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sewing_daily_output_client_key'), ['client_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sewing_daily_output_sewing_order_id'), ['sewing_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sewing_daily_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sewing_daily_output_sewing_order_id'))
        batch_op.drop_index(batch_op.f('ix_sewing_daily_output_client_key'))

    op.drop_table('sewing_daily_output')
    with op.batch_alter_table('inline_inspection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inline_inspection_sewing_order_id'))
        batch_op.drop_index(batch_op.f('ix_inline_inspection_inspection_number'))

    op.drop_table('inline_inspection')
    with op.batch_alter_table('subcontract_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontract_order_subcontractor_id'))
        batch_op.drop_index(batch_op.f('ix_subcontract_order_status'))
        batch_op.drop_index(batch_op.f('ix_subcontract_order_order_number'))

    op.drop_table('subcontract_order')
    with op.batch_alter_table('sewing_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sewing_order_style_id'))
        batch_op.drop_index(batch_op.f('ix_sewing_order_status'))
        batch_op.drop_index(batch_op.f('ix_sewing_order_order_number'))

    op.drop_table('sewing_order')
    with op.batch_alter_table('goods_receipt_roll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_roll_roll_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_roll_purchase_order_line_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_roll_goods_receipt_id'))

    op.drop_table('goods_receipt_roll')
    with op.batch_alter_table('cut_order_size', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cut_order_size_cut_order_id'))

    op.drop_table('cut_order_size')
    with op.batch_alter_table('cut_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cut_issue_roll_id'))
        batch_op.drop_index(batch_op.f('ix_cut_issue_cut_order_id'))

    op.drop_table('cut_issue')
    with op.batch_alter_table('bom_line_size_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_line_size_consumption_size_range_item_id'))
        batch_op.drop_index(batch_op.f('ix_bom_line_size_consumption_bom_line_id'))

    op.drop_table('bom_line_size_consumption')
    with op.batch_alter_table('sales_order_size_cell', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_size_cell_line_id'))

    op.drop_table('sales_order_size_cell')
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_material_id'))

    op.drop_table('purchase_order_line')
    with op.batch_alter_table('goods_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_purchase_order_id'))

    op.drop_table('goods_receipt')
    with op.batch_alter_table('four_point_defect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_four_point_defect_inspection_id'))

    op.drop_table('four_point_defect')
    with op.batch_alter_table('cut_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cut_order_style_id'))
        batch_op.drop_index(batch_op.f('ix_cut_order_status'))
        batch_op.drop_index(batch_op.f('ix_cut_order_order_number'))

    op.drop_table('cut_order')
    with op.batch_alter_table('cost_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_line_cost_sheet_version_id'))

    op.drop_table('cost_line')
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_line_material_id'))
        batch_op.drop_index(batch_op.f('ix_bom_line_bom_version_id'))

    op.drop_table('bom_line')
    with op.batch_alter_table('style_colourway', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_colourway_style_id'))

    op.drop_table('style_colourway')
    with op.batch_alter_table('stock_ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_roll_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_reference_type'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_reference_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_material_id'))

    op.drop_table('stock_ledger_entry')
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_line_style_id'))
        batch_op.drop_index(batch_op.f('ix_sales_order_line_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_sales_order_line_colour_id'))

    op.drop_table('sales_order_line')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_status'))
        batch_op.drop_index(batch_op.f('ix_reservation_roll_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_reference_type'))
        batch_op.drop_index(batch_op.f('ix_reservation_reference_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_material_id'))

    op.drop_table('reservation')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_number'))

    op.drop_table('purchase_order')
    with op.batch_alter_table('four_point_inspection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_four_point_inspection_roll_id'))
        batch_op.drop_index(batch_op.f('ix_four_point_inspection_inspection_number'))

    op.drop_table('four_point_inspection')
    with op.batch_alter_table('final_inspection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_inspection_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_final_inspection_inspection_number'))

    op.drop_table('final_inspection')
    with op.batch_alter_table('cost_sheet_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_sheet_version_version_no'))
        batch_op.drop_index(batch_op.f('ix_cost_sheet_version_style_id'))
        batch_op.drop_index(batch_op.f('ix_cost_sheet_version_status'))

    op.drop_table('cost_sheet_version')
    with op.batch_alter_table('bom_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_version_version_no'))
        batch_op.drop_index(batch_op.f('ix_bom_version_style_id'))

    op.drop_table('bom_version')
    with op.batch_alter_table('ar_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ar_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_ar_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_ar_invoice_customer_id'))

    op.drop_table('ar_invoice')
    with op.batch_alter_table('supplier_material_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_material_type_supplier_id'))

    op.drop_table('supplier_material_type')
    with op.batch_alter_table('style', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_style_number'))

    op.drop_table('style')
    with op.batch_alter_table('size_range_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_size_range_item_size_range_id'))

    op.drop_table('size_range_item')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_status'))
        batch_op.drop_index(batch_op.f('ix_sales_order_order_number'))
        batch_op.drop_index(batch_op.f('ix_sales_order_customer_id'))

    op.drop_table('sales_order')
    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roll_status'))
        batch_op.drop_index(batch_op.f('ix_roll_shade_group'))
        batch_op.drop_index(batch_op.f('ix_roll_roll_number'))
        batch_op.drop_index(batch_op.f('ix_roll_material_id'))
        batch_op.drop_index(batch_op.f('ix_roll_grade'))
        batch_op.drop_index(batch_op.f('ix_roll_goods_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_roll_dye_lot'))

    op.drop_table('roll')
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_line_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_account_id'))

    op.drop_table('journal_line')
    with op.batch_alter_table('ap_bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ap_bill_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_ap_bill_status'))
        batch_op.drop_index(batch_op.f('ix_ap_bill_goods_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_ap_bill_bill_number'))

    op.drop_table('ap_bill')
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_code'))

    op.drop_table('supplier')
    with op.batch_alter_table('sizerange', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sizerange_code'))

    op.drop_table('sizerange')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_code'))

    op.drop_table('season')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_code'))

    op.drop_table('material')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_status'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_reference_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_reference_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_entry_number'))

    op.drop_table('journal_entry')
    with op.batch_alter_table('idempotency_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_key_scope'))
        batch_op.drop_index(batch_op.f('ix_idempotency_key_client_key'))

    op.drop_table('idempotency_key')
    op.drop_table('document_sequence')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_code'))

    op.drop_table('customer')
    with op.batch_alter_table('colour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colour_code'))

    op.drop_table('colour')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_code'))

    op.drop_table('account')
    # ### end Alembic commands ###
